export const SITE_CONFIG = {
  name: 'Charvigne CleanConnect',
  tagline: 'Cleaning Made Easy, Anytime, Anywhere.',
  secondaryTagline: 'Trusted Cleaners. One Tap Away.',
  description: 'Charvigne CleanConnect connects you with trusted, verified cleaners in your area—fast, reliable, and completely stress-free.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://cleanconnect.ng',
  socialLinks: {
    facebook: 'https://facebook.com/charvignecleanconnect',
    instagram: 'https://instagram.com/charvignecleanconnect',
    twitter: 'https://twitter.com/charvigneclean',
    whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '+234816013232',
    tiktok: 'https://tiktok.com/@charvignecleanconnect',
  },
  contact: {
    email: 'charvigneenterprises@gmail.com',
    phone: '+234 816 013 2332',
    whatsapp: '+234816013232',
    address: '13, Power Line Street, Oke Ayo, Ishaga, Lagos, Nigeria',
    responseTime: 'Within 2 hours',
  },
  colors: {
    primary: '#1A5276',
    accent: '#148F77',
    background: '#FDFEFE',
    secondary: '#D6EAF8',
  },
  stats: [
    { number: 500, label: 'Happy Customers', suffix: '+' },
    { number: 100, label: 'Verified Cleaners', suffix: '+' },
    { number: 6, label: 'Service Categories' },
    { number: 7, label: 'Days Weekly Availability' },
  ],
  services: [
    {
      id: 'home-cleaning',
      title: 'Home Cleaning',
      description: 'Professional home cleaning services tailored to your needs.',
      icon: 'Home',
      startingPrice: '₦15,000',
      features: ['Dusting & Vacuuming', 'Kitchen Cleaning', 'Bathroom Sanitization', 'Floor Polishing'],
    },
    {
      id: 'office-cleaning',
      title: 'Office Cleaning',
      description: 'Keep your workspace clean and productive.',
      icon: 'Building2',
      startingPrice: '₦20,000',
      features: ['Desk & Surface Cleaning', 'Floor Maintenance', 'Trash Management', 'Restroom Sanitization'],
    },
    {
      id: 'deep-cleaning',
      title: 'Deep Cleaning',
      description: 'Thorough cleaning for every corner of your space.',
      icon: 'Sparkles',
      startingPrice: '₦40,000',
      features: ['Wall Cleaning', 'Carpet Deep Clean', 'Window Washing', 'Upholstery Cleaning'],
    },
    {
      id: 'post-event-cleaning',
      title: 'Post-Event Cleaning',
      description: 'Quick cleanup after your special event.',
      icon: 'Users',
      startingPrice: '₦25,000',
      features: ['Debris Removal', 'Floor Cleaning', 'Decoration Removal', 'Area Restoration'],
    },
    {
      id: 'move-in-out',
      title: 'Move-In / Move-Out Cleaning',
      description: 'Perfect for new beginnings and transitions.',
      icon: 'Truck',
      startingPrice: '₦35,000',
      features: ['Complete Space Cleaning', 'Appliance Cleaning', 'Carpet Shampooing', 'Final Inspection'],
    },
    {
      id: 'window-cleaning',
      title: 'Window & Exterior Cleaning',
      description: 'Crystal clear windows and pristine exteriors.',
      icon: 'Wind',
      startingPrice: '₦10,000',
      features: ['Window Washing', 'Gutter Cleaning', 'Facade Cleaning', 'Outdoor Space'],
    },
  ],
  testimonials: [
    {
      id: 1,
      name: 'Adebayo Oluwaseun',
      location: 'Lagos',
      rating: 5,
      service: 'Home Cleaning',
      review: 'Outstanding service! The cleaners were professional, punctual, and thorough. My home has never looked better.',
    },
    {
      id: 2,
      name: 'Chioma Eze',
      location: 'Abuja',
      rating: 5,
      service: 'Office Cleaning',
      review: 'Charvigne CleanConnect transformed our office. Our team is more productive in a clean environment.',
    },
    {
      id: 3,
      name: 'Ibrahim Hassan',
      location: 'Port Harcourt',
      rating: 5,
      service: 'Deep Cleaning',
      review: 'Incredible attention to detail. They cleaned areas I didn\'t even know existed in my home!',
    },
    {
      id: 4,
      name: 'Folake Okafor',
      location: 'Lagos',
      rating: 5,
      service: 'Post Event Cleaning',
      review: 'After my event, they cleaned everything perfectly. Highly recommended for anyone hosting events.',
    },
  ],
  faqCustomer: [
    {
      question: 'How do I book a cleaning service?',
      answer: 'Simply click "Book A Cleaner", select your service, choose your preferred date and time, and our system will match you with a verified cleaner. Payment is made after the service is completed.',
    },
    {
      question: 'Are your cleaners verified?',
      answer: 'Yes! All our cleaners undergo thorough background checks, training, and are rated by customers. We only work with trusted professionals.',
    },
    {
      question: 'What payment methods do you accept?',
      answer: 'We accept Bank Transfer, USSD, Card Payments, and Cash On Completion. Payment is secure and protected.',
    },
    {
      question: 'Can I reschedule or cancel my booking?',
      answer: 'Yes, you can reschedule or cancel up to 24 hours before your scheduled cleaning without any penalty.',
    },
    {
      question: 'Do you offer same-day cleaning?',
      answer: 'Yes! We offer same-day and next-day cleaning services in most areas. Availability depends on cleaner availability.',
    },
  ],
  faqCleaner: [
    {
      question: 'How do I apply to become a cleaner?',
      answer: 'Fill out our application form with your details, upload your ID, and provide your cleaning experience. We\'ll review your application within 48 hours.',
    },
    {
      question: 'How much can I earn?',
      answer: 'Earnings vary based on service type and frequency. Most cleaners earn ₦100,000 - ₦500,000 monthly depending on their availability.',
    },
    {
      question: 'Are there hidden charges?',
      answer: 'No hidden charges. We take a transparent commission from bookings. You see exactly what you\'ll earn before accepting a job.',
    },
    {
      question: 'Do I need to provide my own cleaning supplies?',
      answer: 'You can provide your own supplies or we can provide them. It\'s your choice, and both options are available.',
    },
    {
      question: 'What is the minimum experience required?',
      answer: 'We accept cleaners with any level of experience. However, professional cleaners with certifications are prioritized.',
    },
  ],
};
